// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1, arg2) {
  return window['go']['main']['App']['ActivateLicense'](arg1, arg2);
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function ExportCompliancePDF(arg1, arg2) {
  return window['go']['main']['App']['ExportCompliancePDF'](arg1, arg2);
}

export function ExportHTML(arg1, arg2) {
  return window['go']['main']['App']['ExportHTML'](arg1, arg2);
}

export function ExportJSON(arg1, arg2) {
  return window['go']['main']['App']['ExportJSON'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDocContent(arg1) {
  return window['go']['main']['App']['GetDocContent'](arg1);
}

export function GetLicenseStatus() {
  return window['go']['main']['App']['GetLicenseStatus']();
}

export function GetModules() {
  return window['go']['main']['App']['GetModules']();
}

export function OpenImportJSON() {
  return window['go']['main']['App']['OpenImportJSON']();
}

export function RunClientScan(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RunClientScan'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RunScan(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RunScan'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}
