// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateLicense(arg1:string,arg2:string):Promise<main.LicenseStatusDTO>;

export function CancelScan():Promise<void>;

export function ExportCompliancePDF(arg1:string,arg2:string):Promise<string>;

export function ExportHTML(arg1:Array<string>,arg2:Array<string>):Promise<string>;

export function ExportJSON(arg1:Array<string>,arg2:Array<string>):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetDocContent(arg1:string):Promise<string>;

export function GetLicenseStatus():Promise<main.LicenseStatusDTO>;

export function GetModules():Promise<Array<string>>;

export function OpenImportJSON():Promise<Array<main.ScanResultDTO>>;

export function RunClientScan(arg1:Array<string>,arg2:boolean,arg3:number,arg4:number,arg5:number,arg6:string):Promise<Array<main.ScanResultDTO>>;

export function RunScan(arg1:Array<string>,arg2:Array<string>,arg3:boolean,arg4:number,arg5:number,arg6:string):Promise<Array<main.ScanResultDTO>>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;
